"""users table

Revision ID: ff3d1b53326d
Revises: 9ce66404dd5d
Create Date: 2021-10-27 11:18:05.539526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff3d1b53326d'
down_revision = '9ce66404dd5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('last_login_ip', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'active')
    op.drop_column('user', 'last_login_ip')
    op.drop_column('user', 'last_login')
    # ### end Alembic commands ###
